package com.pookie.octfis.data.repository

import android.util.Log
import com.pookie.octfis.data.model.Deal
import com.pookie.octfis.data.remote.ZohoApiService

class DealRepository(private val api: ZohoApiService) {

    companion object {
        val cache = mutableListOf<Deal>()

        // Tracks Deal_Names that were locally edited but not yet confirmed by Zoho
        // (i.e. Zoho still returns the workflow-overwritten name on GET).
        // Key = zohoId, Value = user-entered dealName.
        // Cleared only when Zoho starts returning the correct name itself.
        private val localNameOverrides = mutableMapOf<String, String>()

        fun cleanLookupName(raw: String): String {
            val pattern = Regex("""\s-\s\d{10,}$""")
            return raw.replace(pattern, "").trim()
        }

        /** Call after a successful update to lock in the user's chosen name. */
        fun setLocalNameOverride(zohoId: String, dealName: String) {
            localNameOverrides[zohoId] = dealName
        }

        /**
         * Resolve the display name for a deal coming from Zoho:
         * - If Zoho now returns the correct (non-auto-generated) name, trust it and
         *   clear the local override.
         * - If Zoho still returns the auto-generated "<something> - <zohoId>" pattern,
         *   keep showing the user's locally-saved name instead.
         */
        fun resolveDisplayName(zohoId: String, zohoName: String): String {
            val override = localNameOverrides[zohoId] ?: return zohoName
            // Auto-generated pattern: ends with " - <this deal's zohoId>"
            val isAutoGenerated = zohoName.endsWith(" - $zohoId")
            return if (isAutoGenerated) {
                // Zoho workflow still overwriting — keep showing our local name
                override
            } else {
                // Zoho is now returning a real name — trust it and drop the override
                localNameOverrides.remove(zohoId)
                zohoName
            }
        }
    }

    suspend fun getDeals(page: Int = 1): Result<Pair<List<Deal>, Boolean>> =
        runCatching {
            val response = api.getDeals(page = page, perPage = 100)
            val deals = response.data?.mapIndexed { index, zoho ->
                val resolvedName = resolveDisplayName(zoho.id, zoho.dealName.orEmpty())
                Deal(
                    id              = ((page - 1) * 100) + index + 1,
                    zohoId          = zoho.id,
                    name            = resolvedName.ifEmpty { "(No Name)" },
                    dealName        = resolvedName,
                    accountName     = cleanLookupName(zoho.accountName?.name.orEmpty()),
                    accountZohoId   = zoho.accountName?.id.orEmpty(),
                    contactName     = cleanLookupName(zoho.contactName?.name.orEmpty()),
                    contactZohoId   = zoho.contactName?.id.orEmpty(),
                    amount          = zoho.amount?.let { "%.2f".format(it) }.orEmpty(),
                    closingDate     = zoho.closingDate.orEmpty(),
                    type            = zoho.type.orEmpty().ifEmpty { "-None-" },
                    email           = zoho.email.orEmpty(),
                    phone           = zoho.phone.orEmpty(),
                    dealOwner       = zoho.dealOwner?.name.orEmpty().ifEmpty { "-None-" },
                    dealOwnerId     = zoho.dealOwner?.id.orEmpty(),
                    description     = zoho.description.orEmpty(),
                    stage           = zoho.stage.orEmpty().ifEmpty { "-None-" },
                    leadSource      = zoho.leadSource.orEmpty().ifEmpty { "-None-" },
                    leadSourceDrill = zoho.leadSourceDrill.orEmpty(),
                )
            } ?: emptyList()
            if (page == 1) cache.clear()
            cache.addAll(deals)
            Pair(deals, response.info?.moreRecords ?: false)
        }

    suspend fun createDeal(
        dealName       : String,
        accountName    : String,
        accountZohoId  : String,
        contactName    : String,
        contactZohoId  : String,
        amount         : String,
        closingDate    : String,
        type           : String,
        email          : String,
        dealOwner      : String,
        dealOwnerName  : String = "",
        description    : String,
        stage          : String,
        leadSource     : String,
        leadSourceDrill: String,
    ): Result<String> = runCatching {
        val record = buildMap<String, Any> {
            put("Deal_Name", dealName)
            put("Stage", stage)
            if (closingDate.isNotBlank())                           put("Closing_Date",          closingDate)

            when {
                accountZohoId.isNotBlank() -> put("Account_Name", mapOf("id" to accountZohoId))
                accountName.isNotBlank()   -> put("Account_Name", mapOf("name" to cleanLookupName(accountName)))
            }

            when {
                contactZohoId.isNotBlank() -> put("Contact_Name", mapOf("id" to contactZohoId))
                contactName.isNotBlank()   -> put("Contact_Name", mapOf("name" to cleanLookupName(contactName)))
            }

            amount.toDoubleOrNull()?.let {                          put("Amount",                 it) }
            if (type.isNotBlank() && type != "-None-")              put("Type",                   type)
            if (email.isNotBlank())                                 put("Email",                  email)
            if (description.isNotBlank())                           put("Description",            description)
            if (leadSource.isNotBlank() && leadSource != "-None-")  put("Lead_Source",            leadSource)
            if (leadSourceDrill.isNotBlank())                        put("Lead_Source_Drill_Down", leadSourceDrill)
            if (dealOwner.isNotBlank() && dealOwner != "-None-" && dealOwner.toLongOrNull() != null) put("Owner", mapOf("id" to dealOwner))
        }

        Log.d("DEAL_DEBUG", "CREATE PAYLOAD: $record")

        val response = api.createDeal(mapOf("data" to listOf(record)))
        val result   = response.data?.firstOrNull()
        if (result?.status != "success") {
            val field = result?.details?.apiName ?: "unknown"
            error("${result?.message ?: "Create failed"} [field: $field]")
        }
        val newZohoId = result?.details?.id ?: error("No ID returned from Zoho")
        cache.add(Deal(
            id = cache.size + 1, zohoId = newZohoId, name = dealName, dealName = dealName,
            accountName = cleanLookupName(accountName), accountZohoId = accountZohoId,
            contactName = cleanLookupName(contactName), contactZohoId = contactZohoId,
            amount = amount, closingDate = closingDate,
            type = type.ifEmpty { "-None-" }, email = email,
            dealOwner = dealOwnerName.ifEmpty { "-None-" }, dealOwnerId = dealOwner,
            description = description,
            stage = stage.ifEmpty { "-None-" }, leadSource = leadSource.ifEmpty { "-None-" },
            leadSourceDrill = leadSourceDrill,
        ))
        newZohoId
    }

    suspend fun updateDeal(
        zohoId         : String,
        dealName       : String,
        accountName    : String,
        accountZohoId  : String,
        contactName    : String,
        contactZohoId  : String,
        amount         : String,
        closingDate    : String,
        type           : String,
        email          : String,
        dealOwner      : String,
        dealOwnerName  : String,
        description    : String,
        stage          : String,
        leadSource     : String,
        leadSourceDrill: String,
    ): Result<Unit> = runCatching {
        val record = buildMap<String, Any> {
            put("Deal_Name", dealName)
            put("Stage", stage)
            if (closingDate.isNotBlank())                           put("Closing_Date",          closingDate)

            when {
                accountZohoId.isNotBlank() -> put("Account_Name", mapOf("id" to accountZohoId))
                accountName.isNotBlank()   -> put("Account_Name", mapOf("name" to cleanLookupName(accountName)))
            }

            // Only send Contact_Name when a contact is actually linked —
            // sending it unnecessarily can trigger Zoho's auto-naming on some records.
            if (contactZohoId.isNotBlank() && contactName.isNotBlank()) {
                put("Contact_Name", mapOf("id" to contactZohoId))
            }

            amount.toDoubleOrNull()?.let {                          put("Amount",                 it) }
            if (email.isNotBlank())                                 put("Email",                  email)
            if (description.isNotBlank())                           put("Description",            description)
            if (type.isNotBlank() && type != "-None-")              put("Type",                   type)
            if (leadSource.isNotBlank() && leadSource != "-None-")  put("Lead_Source",            leadSource)
            if (leadSourceDrill.isNotBlank())                        put("Lead_Source_Drill_Down", leadSourceDrill)
            if (dealOwner.isNotBlank() && dealOwner != "-None-" && dealOwner.toLongOrNull() != null) put("Owner", mapOf("id" to dealOwner))
        }

        Log.d("DEAL_DEBUG", "UPDATE zohoId=$zohoId PAYLOAD: $record")

        val response = api.updateDeal(zohoId, mapOf("data" to listOf(record)))
        val result   = response.data?.firstOrNull()
        if (result?.status != "success") {
            val field = result?.details?.apiName ?: "unknown"
            error("${result?.message ?: "Update failed"} [field: $field]")
        }

        // Lock in the user's name so pull-to-refresh doesn't overwrite it with
        // whatever Zoho's workflow puts back.
        setLocalNameOverride(zohoId, dealName)

        Log.d("DEAL_DEBUG", "UPDATE success — applying local cache update for zohoId=$zohoId, dealName=$dealName, ownerName=$dealOwnerName")

        val idx = cache.indexOfFirst { it.zohoId == zohoId }
        if (idx >= 0) {
            cache[idx] = cache[idx].copy(
                name            = dealName.ifEmpty { "(No Name)" },
                dealName        = dealName,
                accountName     = cleanLookupName(accountName),
                accountZohoId   = accountZohoId,
                contactName     = cleanLookupName(contactName),
                contactZohoId   = contactZohoId,
                amount          = amount,
                closingDate     = closingDate,
                type            = type.ifEmpty { "-None-" },
                email           = email,
                dealOwner       = dealOwnerName.ifEmpty { cache[idx].dealOwner },
                dealOwnerId     = dealOwner.ifEmpty { cache[idx].dealOwnerId },
                description     = description,
                stage           = stage.ifEmpty { "-None-" },
                leadSource      = leadSource.ifEmpty { "-None-" },
                leadSourceDrill = leadSourceDrill,
            )
        }
    }
}